Repository flooding-kr/flooding-backend, pull requests merged in 2025-02, with the labels that each got.

#12 Gradle CI 추가
  .github/workflows/gradle-ci.yml
Labels: 1️⃣ Priority: Medium

#7 🔁 홈베이스 예약 기능
  build.gradle.kts
  src/main/kotlin/team/gsm/flooding/domain/attendance/controller/AttendanceController.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/dto/request/ReserveHomebaseTableRequest.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/entity/Attendance.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/entity/HomebaseGroup.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/repository/AttendanceRepository.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/repository/HomebaseGroupRepository.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/usecase/ReserveHomebaseTableUsecase.kt
  src/main/kotlin/team/gsm/flooding/domain/classroom/entity/Classroom.kt
  src/main/kotlin/team/gsm/flooding/domain/classroom/entity/HomebaseTable.kt
  src/main/kotlin/team/gsm/flooding/domain/classroom/repository/ClassroomRepository.kt
  src/main/kotlin/team/gsm/flooding/domain/classroom/repository/HomebaseTableRepository.kt
  src/main/kotlin/team/gsm/flooding/domain/user/entity/User.kt
  src/main/kotlin/team/gsm/flooding/domain/user/repository/UserRepository.kt
  src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
  src/main/kotlin/team/gsm/flooding/global/exception/ExceptionEnum.kt
Labels: 2️⃣ Priority: Low, ✨ Feature

#16 홈베이스 예약 취소 기능
  src/main/kotlin/team/gsm/flooding/domain/attendance/controller/AttendanceController.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/usecase/CancelHomebaseTableUsecase.kt
  src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
  src/main/kotlin/team/gsm/flooding/global/exception/ExceptionEnum.kt
Labels: ✨ Feature

#21 🔀 유저 검색 기능 추가
  src/main/kotlin/team/gsm/flooding/domain/user/controller/UserController.kt
  src/main/kotlin/team/gsm/flooding/domain/user/dto/response/FetchUserInfoResponse.kt
  src/main/kotlin/team/gsm/flooding/domain/user/repository/UserRepository.kt
  src/main/kotlin/team/gsm/flooding/domain/user/usecase/FetchUserUsecase.kt
  src/main/kotlin/team/gsm/flooding/domain/user/usecase/SearchUserUsecase.kt
  src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
  src/main/kotlin/team/gsm/flooding/global/util/StudentUtil.kt
Labels: 2️⃣ Priority: Low, ✨ Feature

#19 홈베이스 예약 조회 기능
  src/main/kotlin/team/gsm/flooding/domain/attendance/controller/AttendanceController.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/dto/request/FindReservedHomebaseTableRequest.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/dto/response/AttendanceResponse.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/dto/response/FindMyReservedHomebaseResponse.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/dto/response/FindReservedHomebaseResponse.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/dto/response/HomebaseTableResponse.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/repository/HomebaseGroupRepository.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/usecase/FindMyReservedHomebaseUsecase.kt
  src/main/kotlin/team/gsm/flooding/domain/attendance/usecase/FindReservedHomebaseTableUsecase.kt
  src/main/kotlin/team/gsm/flooding/domain/classroom/repository/HomebaseTableRepository.kt
  src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
  src/main/kotlin/team/gsm/flooding/global/util/UserUtil.kt
Labels: ✨ Feature

#40 동아리 필터 조회 API
  src/main/kotlin/team/gsm/flooding/domain/club/controller/ClubController.kt
  src/main/kotlin/team/gsm/flooding/domain/club/dto/response/ClubFilterResponse.kt
  src/main/kotlin/team/gsm/flooding/domain/club/dto/response/FindClubFilterResponse.kt
  src/main/kotlin/team/gsm/flooding/domain/club/repository/ClubRepository.kt
  src/main/kotlin/team/gsm/flooding/domain/club/usecase/FindClubFilterUsecase.kt
  src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
Labels: ✨ Feature

#42 ✨ 구성원 추방하기 기능
  src/main/kotlin/team/gsm/flooding/domain/club/controller/ClubController.kt
  src/main/kotlin/team/gsm/flooding/domain/club/usecase/RemoveClubMemberUsecase.kt
  src/main/kotlin/team/gsm/flooding/domain/clubMember/repository/ClubMemberRepository.kt
  src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
  src/main/kotlin/team/gsm/flooding/global/exception/ExceptionEnum.kt
Labels: ✨ Feature

#46 이메일 인증 url 변경
  src/main/kotlin/team/gsm/flooding/domain/auth/controller/AuthController.kt
  src/main/kotlin/team/gsm/flooding/global/thirdparty/email/EmailAdapter.kt
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: ♻️ Refactor

#52 ✨ 동아리 지원하기 기능
  src/main/kotlin/team/gsm/flooding/domain/club/controller/ClubController.kt
  src/main/kotlin/team/gsm/flooding/domain/club/dto/request/ApplyClubRequest.kt
  src/main/kotlin/team/gsm/flooding/domain/club/entity/Club.kt
  src/main/kotlin/team/gsm/flooding/domain/club/usecase/ApplyClubUsecase.kt
  src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
  src/main/kotlin/team/gsm/flooding/global/exception/ExceptionEnum.kt
Labels: ✨ Feature

#56 ✨ 동아리 신청 열기 기능
  src/main/kotlin/team/gsm/flooding/domain/club/controller/ClubController.kt
  src/main/kotlin/team/gsm/flooding/domain/club/usecase/OpenClubUsecase.kt
  src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
Labels: ✨ Feature

#60 동아리 신청 마감 API
  src/main/kotlin/kr/flooding/backend/domain/club/controller/ClubController.kt
  src/main/kotlin/kr/flooding/backend/domain/club/usecase/CloseClubUsecase.kt
  src/main/kotlin/kr/flooding/backend/global/config/SecurityConfig.kt
Labels: ✨ Feature
